### ISSUE TITLE
Problem Initializing the Program 

### ISSUE THREAD

**Issue by MasamioNakada** [ThatSnail/drummer#1]
### When I try to run the gui.py program, I get this result
```
$ py gui.py
Settings
====================
a: 0.5
K: 20.0
c: 70.71067811865476
rcount: 30.0
thetacount: 60.0
m_max: 2
n_max: 5
Traceback (most recent call last):
  File "C:\Users\MASAO\drummer\gui.py", line 199, in <module>
    gui = Gui(sys.argv)
  File "C:\Users\MASAO\drummer\gui.py", line 89, in __init__
    self._on_drum_change()
  File "C:\Users\MASAO\drummer\gui.py", line 131, in _on_drum_change
    self.drum = Drum(a=a, K=K, c=c, rcount=rcount, \
  File "C:\Users\MASAO\drummer\drum.py", line 46, in __init__
    self.rs = np.linspace(0, a, self.rcount)
  File "<__array_function__ internals>", line 5, in linspace
  File "C:\Users\MASAO\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\core\function_base.py", line 120, in linspace
    num = operator.index(num)
TypeError: 'float' object cannot be interpreted as an integer
```

**Comment by roytu** [comment]
Thanks for the issue. It's been awhile since I've written this, so can't fully test it right now, but looks like it's complaining about this line:

```
self.rs = np.linspace(0, a, self.rcount)
```

where `self.rcount` ought to be an integer.

Quick fix is to change this line ( https://github.com/roytu/drummer/blob/master/gui.py#L131-L132 ) from:

```
self.drum = Drum(a=a, K=K, c=c, rcount=rcount, \
                         thetacount=thetacount, m_max=m_max, n_max=n_max)
```

to

```
self.drum = Drum(a=a, K=K, c=c, rcount=int(rcount), \
                         thetacount=int(thetacount), m_max=m_max, n_max=n_max)
```

**Comment by roytu** [comment]
Just merged a fix, let me know if you run into any more issues :)
